[package]
name = "rust-candle-lib-tutorial"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
candle-core = { version = "0.11.0", features = ["metal"] }
candle-nn = { version = "0.11.0", features = ["metal"] }
image = { version = "0.25.5", default-features = false, features = ["png"] }
